name: sudoku
description: Sudoku game for Android and iOS (Flutter).
publish_to: "none"
version: 0.0.15+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.0
  google_mobile_ads: ^5.1.0
  flutter_riverpod: ^2.4.9
  sudoku_dart: ^1.2.0
  hive_flutter: ^1.1.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.example
    - .env
